name: examplearch
description: Example Project for My Architecture
version: 1.0.1+2
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.1.0
  device_info_plus: ^10.1.0
  dio: 5.4.3
  firebase_analytics: ^11.0.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  firebase_remote_config: ^5.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  injectable: ^2.3.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  package_info_plus: ^8.0.0
  pretty_dio_logger: ^1.3.1
  route_map: ^0.0.17
  shimmer: ^3.0.0
  sign_in_button: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0
  # flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.8.0
  route_map_generator: ^0.0.17

flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/images/
