// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get currentDevPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidDev;
      case TargetPlatform.iOS:
        return iosDev;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhJnyQr78f47nY_Igj_PGqEGM5i3Ec7do',
    appId: '1:357999879430:android:4c5d355a5f0f0c34bfaa87',
    messagingSenderId: '357999879430',
    projectId: 'examplearchl-589c0',
    storageBucket: 'examplearchl-589c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAeMfxfiJfQteahr-Ru4o3epizb3CJwbU',
    appId: '1:357999879430:ios:789957897d302300bfaa87',
    messagingSenderId: '357999879430',
    projectId: 'examplearchl-589c0',
    storageBucket: 'examplearchl-589c0.appspot.com',
    androidClientId:
        '357999879430-4k1aadlnj0u5b9iivpcd8mikk2l9flo8.apps.googleusercontent.com',
    iosClientId:
        '357999879430-gprbcdl8818gn73ll5n174rvugkmdq7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.gym-pol',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyBhJnyQr78f47nY_Igj_PGqEGM5i3Ec7do',
    appId: '1:357999879430:android:4c5d355a5f0f0c34bfaa87',
    messagingSenderId: '357999879430',
    projectId: 'examplearchl-589c0',
    storageBucket: 'examplearchl-589c0.appspot.com',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyCAeMfxfiJfQteahr-Ru4o3epizb3CJwbU',
    appId: '1:357999879430:ios:c197d051faf4bbddbfaa87',
    messagingSenderId: '357999879430',
    projectId: 'examplearchl-589c0',
    storageBucket: 'examplearchl-589c0.appspot.com',
    androidClientId:
        '357999879430-4k1aadlnj0u5b9iivpcd8mikk2l9flo8.apps.googleusercontent.com',
    iosClientId:
        '357999879430-i85kbldrtga2j4ttsnf9vm1lau4poshe.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.gym-pol.dev',
  );
}
