// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get currentDevPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidDev;
      case TargetPlatform.iOS:
        return iosDev;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'X',
    appId: 'X',
    messagingSenderId: 'X',
    projectId: 'examplearchl-589c0',
    storageBucket: 'examplearchl-589c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'X',
    appId: 'X',
    messagingSenderId: 'X',
    projectId: 'examplearchl-589c0',
    storageBucket: 'examplearchl-589c0.appspot.com',
    androidClientId: 'X.apps.googleusercontent.com',
    iosClientId: 'X.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.gym-pol',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'X',
    appId: 'X',
    messagingSenderId: '357999879430',
    projectId: 'examplearchl-589c0',
    storageBucket: 'X-589c0.appspot.com',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'X',
    appId: 'X',
    messagingSenderId: 'X',
    projectId: 'examplearchl-589c0',
    storageBucket: 'examplearchl-589c0.appspot.com',
    androidClientId: 'X.apps.googleusercontent.com',
    iosClientId: 'X.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.gym-pol',
  );
}
