name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - run: flutter --version
     - name: Install dependencies
       run: flutter pub get
     - name: Build Runner
       run: flutter pub run build_runner build --delete-conflicting-outputs
     - name: APK Build
       run: flutter build apk --release

